# Generated by Django 3.2.4 on 2021-07-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Name')),
                ('detail', models.CharField(blank=True, db_column='detail', max_length=100, null=True, verbose_name='Detail')),
                ('picture', models.CharField(blank=True, db_column='picture', max_length=100, null=True, verbose_name='Picture')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('periodEnd', models.DateTimeField(blank=True, db_column='periodEnd', null=True, verbose_name='Periode End')),
                ('periodStart', models.DateTimeField(blank=True, db_column='periodStart', null=True, verbose_name='Periode Start')),
                ('status', models.CharField(blank=True, db_column='status', max_length=100, null=True, verbose_name='Status')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
            ],
            options={
                'db_table': 'tbl_campaign',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Name')),
                ('sort', models.IntegerField(blank=True, db_column='sort', null=True, verbose_name='Sort')),
                ('color', models.CharField(blank=True, db_column='color', max_length=100, null=True, verbose_name='Color')),
                ('availability', models.CharField(blank=True, db_column='availability', max_length=100, null=True, verbose_name='Availability')),
                ('picture', models.CharField(blank=True, db_column='picture', max_length=100, null=True, verbose_name='Picture')),
                ('isActive', models.BooleanField(db_column='isActive', default=False, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'tbl_mastercategory',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Name')),
                ('detail', models.CharField(blank=True, db_column='detail', max_length=100, null=True, verbose_name='Detail')),
                ('click', models.IntegerField(blank=True, db_column='click', null=True, verbose_name='Click')),
                ('picture', models.CharField(blank=True, db_column='picture', max_length=100, null=True, verbose_name='Picture')),
                ('redirectUrl', models.CharField(blank=True, db_column='redirectUrl', max_length=400, null=True, verbose_name='Redirect URL')),
                ('uniqueCode', models.CharField(blank=True, db_column='uniqueCode', max_length=100, null=True, verbose_name='Unique Code')),
                ('periodStart', models.DateTimeField(blank=True, db_column='periodStart', null=True, verbose_name='Period Start')),
                ('periodEnd', models.DateTimeField(blank=True, db_column='periodEnd', null=True, verbose_name='Period End')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('status', models.CharField(blank=True, db_column='status', max_length=100, null=True, verbose_name='Status')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('campaign', models.ForeignKey(db_column='campaignId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.campaign')),
            ],
            options={
                'db_table': 'tbl_channel',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Name')),
                ('type', models.CharField(blank=True, db_column='type', max_length=100, null=True, verbose_name='Type')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
            ],
            options={
                'db_table': 'tbl_field',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Name')),
                ('detail', models.CharField(blank=True, db_column='detail', max_length=1000, null=True, verbose_name='Detail')),
                ('type', models.CharField(blank=True, db_column='type', max_length=100, null=True, verbose_name='Type')),
                ('pageUrl', models.CharField(blank=True, db_column='pageUrl', max_length=400, null=True, verbose_name='Page Url')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('updatedAt', models.DateTimeField(blank=True, db_column='updatedAt', null=True, verbose_name='Updated At')),
                ('updatedBy', models.IntegerField(blank=True, db_column='updatedBy', null=True, verbose_name='Updated By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
            ],
            options={
                'db_table': 'tbl_form',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Name')),
                ('sort', models.IntegerField(blank=True, db_column='sort', null=True, verbose_name='Sort')),
                ('type', models.CharField(blank=True, db_column='type', max_length=100, null=True, verbose_name='Type')),
                ('picture', models.CharField(blank=True, db_column='picture', max_length=100, null=True, verbose_name='Picture')),
                ('isActive', models.BooleanField(db_column='isActive', default=False, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'tbl_mastermedia',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Name')),
                ('detail', models.CharField(blank=True, db_column='detail', max_length=100, null=True, verbose_name='Detail')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('periodEnd', models.DateTimeField(blank=True, db_column='periodEnd', null=True, verbose_name='Periode End')),
                ('periodStart', models.DateTimeField(blank=True, db_column='periodStart', null=True, verbose_name='Periode Start')),
            ],
            options={
                'db_table': 'tbl_project',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('userId', models.IntegerField(blank=True, db_column='userId', null=True, verbose_name='User Id')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('project', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.project')),
            ],
            options={
                'db_table': 'tbl_userproject',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Name')),
                ('point', models.IntegerField(blank=True, db_column='point', null=True, verbose_name='Sort')),
                ('detail', models.CharField(blank=True, db_column='detail', max_length=100, null=True, verbose_name='Detail')),
                ('sort', models.IntegerField(blank=True, db_column='sort', null=True, verbose_name='Sort')),
                ('color', models.CharField(blank=True, db_column='color', max_length=100, null=True, verbose_name='Color')),
                ('category', models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api_projects.category')),
            ],
            options={
                'db_table': 'tbl_masterstatus',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.IntegerField(blank=True, db_column='teamId', null=True, verbose_name='Team Id')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('project', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.project')),
            ],
            options={
                'db_table': 'tbl_projectteam',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True, db_column='point', null=True, verbose_name='Point')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Name')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('color', models.CharField(blank=True, db_column='color', max_length=100, null=True, verbose_name='Color')),
                ('sort', models.IntegerField(blank=True, db_column='sort', null=True, verbose_name='Sort')),
                ('category', models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_projects.category')),
                ('project', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.project')),
            ],
            options={
                'db_table': 'tbl_projectstatus',
            },
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField(blank=True, db_column='productId', null=True, verbose_name='Product Id')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('project', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.project')),
            ],
            options={
                'db_table': 'tbl_projectProduct',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('field', models.ForeignKey(db_column='fieldId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.field')),
                ('form', models.ForeignKey(db_column='formId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.form')),
            ],
            options={
                'db_table': 'tbl_formfield',
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.IntegerField(blank=True, db_column='memberId', null=True, verbose_name='Account Id')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('channel', models.ForeignKey(db_column='channelId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.channel')),
            ],
            options={
                'db_table': 'tbl_channelmember',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='form',
            field=models.ForeignKey(blank=True, db_column='formId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_projects.form'),
        ),
        migrations.AddField(
            model_name='channel',
            name='media',
            field=models.ForeignKey(blank=True, db_column='mediaId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_projects.media'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_projects.project'),
        ),
    ]
