# Generated by Django 3.2.4 on 2021-07-22 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='isActive',
            field=models.BooleanField(db_column='isActive', default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='click',
            field=models.IntegerField(blank=True, db_column='click', default=0, null=True, verbose_name='Click'),
        ),
        migrations.AlterField(
            model_name='media',
            name='isActive',
            field=models.BooleanField(db_column='isActive', default=True, verbose_name='Is Active'),
        ),
        migrations.CreateModel(
            name='ChannelClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('channel', models.ForeignKey(db_column='channelId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.channel')),
            ],
            options={
                'db_table': 'tbl_channelclick',
            },
        ),
    ]
