# Generated by Django 3.2.4 on 2021-08-16 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0002_auto_20210722_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.IntegerField(blank=True, db_column='teamId', null=True, verbose_name='Team Id')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
            ],
            options={
                'db_table': 'tbl_channelgroup',
            },
        ),
        migrations.CreateModel(
            name='ChannelMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Name')),
                ('sort', models.IntegerField(blank=True, db_column='sort', null=True, verbose_name='Sort')),
                ('type', models.CharField(blank=True, db_column='type', max_length=100, null=True, verbose_name='Type')),
                ('picture', models.CharField(blank=True, db_column='picture', max_length=100, null=True, verbose_name='Picture')),
                ('isActive', models.BooleanField(db_column='isActive', default=True, verbose_name='Is Active')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
            ],
            options={
                'db_table': 'tbl_channelmedia',
            },
        ),
        migrations.CreateModel(
            name='ChannelSettingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_redistribution', models.BooleanField(db_column='enable_redistribution', default=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=100, null=True)),
                ('status_distribution', models.CharField(blank=True, db_column='status_distribution', default='enable', max_length=100, null=True)),
                ('percentage', models.CharField(blank=True, db_column='percentage', max_length=100, null=True)),
                ('idleDuration', models.CharField(blank=True, db_column='idleDuration', max_length=100, null=True)),
                ('startTime', models.CharField(blank=True, db_column='startTime', max_length=100, null=True)),
                ('endTime', models.CharField(blank=True, db_column='endTime', max_length=100, null=True)),
                ('userId', models.IntegerField(blank=True, db_column='userId', null=True, verbose_name='User Id')),
                ('teamId', models.IntegerField(blank=True, db_column='teamId', null=True, verbose_name='Team Id')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
            ],
            options={
                'db_table': 'tbl_channelsettingmember',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='distribution_type',
            field=models.CharField(blank=True, db_column='distribution_type', max_length=100, null=True, verbose_name='Distribution Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='running', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='running', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='running', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='uniqueCode',
            field=models.UUIDField(db_column='uniqueCode', default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ChannelMember',
        ),
        migrations.AddField(
            model_name='channelsettingmember',
            name='channel',
            field=models.ForeignKey(db_column='channelId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.channel'),
        ),
        migrations.AddField(
            model_name='channelmedia',
            name='channel',
            field=models.ForeignKey(db_column='channelId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.channel'),
        ),
        migrations.AddField(
            model_name='channelgroup',
            name='channel',
            field=models.ForeignKey(db_column='channelId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.channel'),
        ),
    ]
