# Generated by Django 3.2.4 on 2021-08-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0004_category_enablereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='alias',
            field=models.CharField(blank=True, db_column='alias', max_length=100, null=True, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='field',
            name='displayedas',
            field=models.CharField(blank=True, db_column='displayedas', max_length=100, null=True, verbose_name='Displayedas'),
        ),
        migrations.AddField(
            model_name='field',
            name='mandatory',
            field=models.BooleanField(blank=True, db_column='mandatory', null=True, verbose_name='Mandatory'),
        ),
        migrations.AddField(
            model_name='field',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='isActive',
            field=models.BooleanField(db_column='isActive', default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='status',
            name='tenantCategory',
            field=models.CharField(blank=True, db_column='tenantCategory', max_length=100, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='status',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api_projects.category'),
        ),
    ]
