# Generated by Django 3.2.4 on 2021-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0005_auto_20210819_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsettingmember',
            name='enable_redistribution',
        ),
        migrations.RemoveField(
            model_name='channelsettingmember',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='channelsettingmember',
            name='idleDuration',
        ),
        migrations.RemoveField(
            model_name='channelsettingmember',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='channelsettingmember',
            name='teamId',
        ),
        migrations.AddField(
            model_name='channel',
            name='enable_redistribution',
            field=models.BooleanField(blank=True, db_column='enable_redistribution', null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='endTime',
            field=models.TimeField(blank=True, db_column='endTime', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='idleDuration',
            field=models.CharField(blank=True, db_column='idleDuration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='startTime',
            field=models.TimeField(blank=True, db_column='startTime', max_length=100, null=True),
        ),
    ]
