# Generated by Django 3.2.4 on 2021-08-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0006_auto_20210823_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='totalChannel',
            field=models.IntegerField(blank=True, db_column='totalChannel', null=True, verbose_name='totalChannel'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='totalLead',
            field=models.IntegerField(blank=True, db_column='totalLead', null=True, verbose_name='total Lead'),
        ),
        migrations.AddField(
            model_name='channel',
            name='leadRate',
            field=models.CharField(blank=True, db_column='leadRate', default=None, max_length=100, null=True, verbose_name='lead_rate'),
        ),
        migrations.AddField(
            model_name='channel',
            name='totalLead',
            field=models.IntegerField(blank=True, db_column='totalLead', null=True, verbose_name='total Lead'),
        ),
        migrations.AddField(
            model_name='project',
            name='totalCampaign',
            field=models.IntegerField(blank=True, db_column='totalCampaign', null=True, verbose_name='total Campaign'),
        ),
        migrations.AddField(
            model_name='project',
            name='totalGroup',
            field=models.IntegerField(blank=True, db_column='totalGroup', null=True, verbose_name='total Group'),
        ),
        migrations.AddField(
            model_name='project',
            name='totalLead',
            field=models.IntegerField(blank=True, db_column='totalLead', null=True, verbose_name='total Lead'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='detail',
            field=models.CharField(blank=True, db_column='detail', max_length=500, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='detail',
            field=models.CharField(blank=True, db_column='detail', max_length=500, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='form',
            name='detail',
            field=models.CharField(blank=True, db_column='detail', max_length=500, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=models.CharField(blank=True, db_column='detail', max_length=500, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='status',
            name='detail',
            field=models.CharField(blank=True, db_column='detail', max_length=500, null=True, verbose_name='Detail'),
        ),
    ]
