# Generated by Django 3.2.4 on 2021-08-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0008_auto_20210824_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='distribution_type',
            field=models.CharField(blank=True, db_column='distributionType', max_length=100, null=True, verbose_name='Distribution Type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='enable_redistribution',
            field=models.BooleanField(blank=True, db_column='enableRedistribution', null=True),
        ),
    ]
