# Generated by Django 3.2.4 on 2021-08-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0009_auto_20210824_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='form',
            name='updatedBy',
        ),
        migrations.AddField(
            model_name='form',
            name='modifiedAt',
            field=models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At'),
        ),
        migrations.AddField(
            model_name='form',
            name='modifiedBy',
            field=models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By'),
        ),
    ]
