# Generated by Django 3.2.4 on 2021-08-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0010_auto_20210824_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='distribution_type',
            new_name='distributionType',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='enable_redistribution',
            new_name='enableRedistribution',
        ),
    ]
