# Generated by Django 3.2.4 on 2021-08-29 13:44

import api_projects.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0011_auto_20210824_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ManyToManyField(through='api_projects.FormField', to='api_projects.Form'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='uniqueCode',
            field=models.CharField(db_column='uniqueCode', default=api_projects.utils.get_uuid, editable=False, max_length=100, unique=True),
        ),
    ]
