# Generated by Django 3.2.4 on 2021-09-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0014_auto_20210831_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='detail',
            field=models.CharField(blank=True, db_column='detail', max_length=1000, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='channelsettingmember',
            name='channel',
            field=models.ForeignKey(blank=True, db_column='channelId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_projects.channel'),
        ),
    ]
