# Generated by Django 3.2.4 on 2021-09-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0015_auto_20210902_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='accountId',
            field=models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id'),
        ),
        migrations.AlterField(
            model_name='media',
            name='isActive',
            field=models.BooleanField(blank=True, db_column='isActive', default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.DeleteModel(
            name='ChannelMedia',
        ),
    ]
