# Generated by Django 3.2.4 on 2021-09-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0016_auto_20210902_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, db_column='point', null=True, verbose_name='Point')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('name', models.CharField(blank=True, db_column='name', max_length=1000, null=True, verbose_name='Name')),
                ('detail', models.CharField(blank=True, db_column='detail', max_length=1000, null=True, verbose_name='Detail')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('color', models.CharField(blank=True, db_column='color', max_length=1000, null=True, verbose_name='Color')),
                ('sort', models.IntegerField(blank=True, db_column='sort', null=True, verbose_name='Sort')),
                ('category', models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_projects.category')),
            ],
            options={
                'db_table': 'tbl_customstatus',
            },
        ),
    ]
