# Generated by Django 3.2.4 on 2021-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0020_alter_channel_leadrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='leadRate',
            field=models.IntegerField(blank=True, db_column='leadRate', default=0, null=True, verbose_name='lead_rate'),
        ),
    ]
