# Generated by Django 3.2.4 on 2022-01-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0022_auto_20220125_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='script',
            field=models.CharField(blank=True, db_column='script', max_length=1000, null=True, unique=True, verbose_name='Script'),
        ),
    ]
