# Generated by Django 3.2.4 on 2022-02-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0026_auto_20220127_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='periodStart',
            field=models.DateTimeField(blank=True, db_column='periodStart', editable=False, null=True, verbose_name='Periode Start'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='periodStart',
            field=models.DateTimeField(blank=True, db_column='periodStart', editable=False, null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='periodStart',
            field=models.DateTimeField(blank=True, db_column='periodStart', editable=False, null=True, verbose_name='Periode Start'),
        ),
    ]
