# Generated by Django 3.2.4 on 2022-03-09 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0027_auto_20220215_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duplicate_lead',
            field=models.BooleanField(db_column='duplicate_lead', default=False),
        ),
        migrations.CreateModel(
            name='ProjectDuplicateStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, db_column='point', null=True, verbose_name='Point')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('name', models.CharField(blank=True, db_column='name', max_length=1000, null=True, verbose_name='Name')),
                ('detail', models.CharField(blank=True, db_column='detail', max_length=1000, null=True, verbose_name='Detail')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('color', models.CharField(blank=True, db_column='color', max_length=1000, null=True, verbose_name='Color')),
                ('sort', models.IntegerField(blank=True, db_column='sort', null=True, verbose_name='Sort')),
                ('category', models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_projects.category')),
                ('project', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.project')),
            ],
            options={
                'db_table': 'tbl_project_duplicatestatus',
            },
        ),
    ]
