# Generated by Django 3.2.4 on 2022-03-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0029_auto_20220315_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='script',
        ),
    ]
