# Generated by Django 3.2.4 on 2022-03-28 05:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0030_remove_form_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('userId', models.IntegerField(blank=True, db_column='userId', null=True, verbose_name='User Id')),
                ('role', models.CharField(blank=True, db_column='role', max_length=100, null=True)),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('project', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='api_projects.project')),
            ],
            options={
                'db_table': 'tbl_projectadmin',
            },
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
