# Generated by Django 3.2.4 on 2022-03-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0033_projectadmin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectadmin',
            name='role',
        ),
        migrations.AddField(
            model_name='projectadmin',
            name='ref_id',
            field=models.CharField(blank=True, db_column='ref_id', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectadmin',
            name='project',
            field=models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_projects.project'),
        ),
    ]
