# Generated by Django 3.2.4 on 2022-03-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0034_auto_20220328_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectadmin',
            name='modifiedAt',
            field=models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At'),
        ),
        migrations.AddField(
            model_name='projectadmin',
            name='modifiedBy',
            field=models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By'),
        ),
    ]
