# Generated by Django 3.2.4 on 2022-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0035_auto_20220330_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectadmin',
            name='mask_phone',
            field=models.BooleanField(db_column='mask_phone', default=False, verbose_name=' Mask phone'),
        ),
    ]
