# Generated by Django 3.2.4 on 2023-05-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0036_projectadmin_mask_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.CharField(blank=True, db_column='picture', max_length=1000, null=True, verbose_name='Picture'),
        ),
    ]
