# Generated by Django 3.2.4 on 2023-10-02 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0037_project_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(blank=True, db_column='userId', null=True, verbose_name='User Id')),
                ('distribution', models.CharField(blank=True, db_column='distribution', max_length=1000, null=True)),
                ('campaignId', models.CharField(blank=True, db_column='campaignids', max_length=1000, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=1000, null=True)),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
            ],
            options={
                'db_table': 'tbl_distribution_usersettings',
            },
        )
    ]
