# Generated by Django 3.2.4 on 2023-10-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0038_auto_20231002_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdistribution',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=100000, null=True),
        ),
    ]
